[package]
name = "slicenator"
authors = ["PointyFluff@github.com"]
version = "0.3.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
